spring:
  application:
    name: springboot-amqp
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mq:
  config:
    exchange: log.direct
    queue:
      info: log.info
        routing:
          key: log.info.routing.key
      error: log.error
        routing:
          key: log.error.routing.key